<a href="https://colab.research.google.com/github/besufikad/studying/blob/master/colabtutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf 

In [3]:
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
x

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [4]:
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [5]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])

In [6]:
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [7]:
x = tf.random.poisson((3, 2), 3)

In [8]:
x

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [2., 6.],
       [6., 4.]], dtype=float32)>

In [9]:
h = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])

In [10]:
z = tf.add(h, y)

In [11]:
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>